ar_layers: &id001
- 10
- 20
- 30
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: null
  n_lags: 10
  reg_lambda: null
config_events: null
config_holidays: !!python/object:neuralprophet.configure.Holidays
  country: IR
  holiday_names: !!set
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u062A\u0627\u0633\u0648\u0639\u0627": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0632\u0627\u062F\u0631\u0648\u0632 \u062D\u062C\u062A \u0628\u0646 \u0627\u0644\u062D\u0633\u0646": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0632\u0627\u062F\u0631\u0648\u0632 \u0639\u0644\u06CC \u0628\u0646 \u0627\u0628\u06CC\u200C\u0637\u0627\u0644\u0628": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0632\u0627\u062F\u0631\u0648\u0632 \u0639\u0644\u06CC \u0628\u0646 \u0627\u0628\u06CC\u200C\u0637\u0627\u0644\u0628; \u062F\u0631\u06AF\u0630\u0634\u062A \u0633\u06CC\u062F \u0631\u0648\u062D\u200C\u0627\u0644\u0644\u0647 \u062E\u0645\u06CC\u0646\u06CC": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0632\u0627\u062F\u0631\u0648\u0632 \u0639\u0644\u06CC \u0628\u0646 \u0627\u0628\u06CC\u200C\u0637\u0627\u0644\u0628; \u0645\u0644\u06CC\u200C\u0634\u062F\u0646 \u0635\u0646\u0639\u062A \u0646\u0641\u062A": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0632\u0627\u062F\u0631\u0648\u0632 \u0645\u062D\u0645\u062F \u0648 \u062C\u0639\u0641\u0631 \u0635\u0627\u062F\u0642": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0639\u06CC\u062F \u063A\u062F\u06CC\u0631": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0639\u06CC\u062F \u0641\u0637\u0631": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0639\u06CC\u062F \u0641\u0637\u0631; \u062A\u0638\u0627\u0647\u0631\u0627\u062A \u06F1\u06F5 \u062E\u0631\u062F\u0627\u062F": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0639\u06CC\u062F \u0641\u0637\u0631; \u062F\u0631\u06AF\u0630\u0634\u062A \u0633\u06CC\u062F \u0631\u0648\u062D\u200C\u0627\u0644\u0644\u0647 \u062E\u0645\u06CC\u0646\u06CC": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0639\u06CC\u062F \u0642\u0631\u0628\u0627\u0646": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0645\u0628\u0639\u062B": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0645\u0628\u0639\u062B; \u0646\u0648\u0631\u0648\u0632": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u0686\u0647\u0644\u0645 \u062D\u0633\u06CC\u0646 \u0628\u0646 \u0639\u0644\u06CC \u0627\u0631\u0628\u0639\u06CC\u0646": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u062C\u0639\u0641\u0631 \u0635\u0627\u062F\u0642": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u062D\u0633\u0646 \u0639\u0633\u06A9\u0631\u06CC": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u062D\u0633\u0646 \u0645\u062C\u062A\u0628\u06CC \u0648 \u062F\u0631\u06AF\u0630\u0634\u062A \u0645\u062D\u0645\u062F": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u062D\u0633\u06CC\u0646 \u0628\u0646 \u0639\u0644\u06CC\u060C \u0639\u0627\u0634\u0648\u0631\u0627": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u0639\u0644\u06CC \u0628\u0646 \u0627\u0628\u06CC\u200C\u0637\u0627\u0644\u0628": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u0639\u0644\u06CC \u0628\u0646 \u0627\u0628\u06CC\u200C\u0637\u0627\u0644\u0628; \u062A\u0638\u0627\u0647\u0631\u0627\u062A \u06F1\u06F5 \u062E\u0631\u062F\u0627\u062F": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u0639\u0644\u06CC \u0628\u0646 \u0627\u0628\u06CC\u200C\u0637\u0627\u0644\u0628; \u0631\u0648\u0632 \u062C\u0645\u0647\u0648\u0631\u06CC \u0627\u0633\u0644\u0627\u0645\u06CC": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u0639\u0644\u06CC \u0628\u0646 \u0645\u0648\u0633\u06CC \u0627\u0644\u0631\u0636\u0627": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u0641\u0627\u0637\u0645\u0647 \u0632\u0647\u0631\u0627": null
    "(\u062A\u062E\u0645\u06CC\u0646 \u0632\u062F\u0647) \u06A9\u0634\u062A\u0647\u200C\u0634\u062F\u0646 \u0641\u0627\u0637\u0645\u0647 \u0632\u0647\u0631\u0627; \u0646\u0648\u0631\u0648\u0632": null
    "\u062A\u0638\u0627\u0647\u0631\u0627\u062A \u06F1\u06F5 \u062E\u0631\u062F\u0627\u062F": null
    "\u062F\u0631\u06AF\u0630\u0634\u062A \u0633\u06CC\u062F \u0631\u0648\u062D\u200C\u0627\u0644\u0644\u0647 \u062E\u0645\u06CC\u0646\u06CC": null
    "\u0631\u0648\u0632 \u062C\u0645\u0647\u0648\u0631\u06CC \u0627\u0633\u0644\u0627\u0645\u06CC": null
    "\u0631\u0648\u0632 \u0637\u0628\u06CC\u0639\u062A": null
    "\u0645\u0644\u06CC\u200C\u0634\u062F\u0646 \u0635\u0646\u0639\u062A \u0646\u0641\u062A": null
    "\u0646\u0648\u0631\u0648\u0632": null
    "\u067E\u06CC\u0631\u0648\u0632\u06CC \u0627\u0646\u0642\u0644\u0627\u0628 \u06F5\u06F7": null
  lower_window: 0
  mode: additive
  reg_lambda: null
  upper_window: 0
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id003 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 386985600000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1325376000000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          RrJJmyDf6D8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAAAAA=
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id003
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                RrJJmyDf6D8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAAAAAAA=
  normalize: auto
  unknown_data_normalization: false
config_regressors: !!python/object:neuralprophet.configure.ConfigFutureRegressors
  d_hidden: 4
  model: linear
  num_hidden_layers: 2
  regressors: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: false
  daily_global_local: auto
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: auto
        condition_name: null
        global_local: global
        period: 365.25
        resolution: 6
    - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: auto
        condition_name: null
        global_local: global
        period: 7
        resolution: 3
  reg_lambda: 0
  seasonality_local_reg: false
  weekly_arg: auto
  weekly_global_local: auto
  yearly_arg: auto
  yearly_global_local: auto
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 500
  epochs: 70
  lambda_delay: 35
  learning_rate: 0.01
  loss_func: !!python/object:neuralprophet.custom_loss_metrics.PinballLoss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - - - loss_func
        - !!python/object:torch.nn.modules.loss.SmoothL1Loss
          _backward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _buffers: !!python/object/apply:collections.OrderedDict
          - []
          _forward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
          - []
          _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
          - []
          _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
          - []
          _is_full_backward_hook: null
          _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _modules: !!python/object/apply:collections.OrderedDict
          - []
          _non_persistent_buffers_set: !!set {}
          _parameters: !!python/object/apply:collections.OrderedDict
          - []
          _state_dict_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          beta: 0.3
          reduction: none
          training: true
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    quantiles: &id004
    - 0.5
    - 0.05
    - 0.95
    reduction: mean
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 4461
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles: *id004
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: false
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: linear
  n_changepoints: 10
  trend_global_local: global
  trend_local_reg: false
  trend_reg: 1.0e-06
  trend_reg_threshold: null
id_list:
- __df__
lagged_reg_layers: []
max_lags: 10
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 10
n_lags: 10
num_seasonalities_modelled: 1
num_seasonalities_modelled_dict: !!python/object/apply:collections.OrderedDict
- - - yearly
    - 1
  - - weekly
    - 1
  - - daily
    - 1
num_trends_modelled: 1
